/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package me.rudraksha007.billgenerator.GUI;

import me.rudraksha007.billgenerator.utilities.DataManager;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author rudra
 */
public class Summary extends javax.swing.JFrame {

    DataManager data = new DataManager();
    boolean starting = true; //INFO: don't remove, adds all elements to CMBs
    /** Creates new form Summary */
    public Summary() {
        initComponents();
        setTableData(data.get("SELECT * FROM Transactions"));
        starting = false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFilters = new javax.swing.JPanel();
        cmbParty = new javax.swing.JComboBox<>();
        cmbSupplier = new javax.swing.JComboBox<>();
        cmbLocation = new javax.swing.JComboBox<>();
        cmbRemark = new javax.swing.JComboBox<>();
        pnlData = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        pnlSum = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        cmbParty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Party" }));
        cmbParty.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPartyItemStateChanged(evt);
            }
        });

        cmbSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supplier" }));
        cmbSupplier.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSupplierItemStateChanged(evt);
            }
        });

        cmbLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Location" }));
        cmbLocation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbLocationItemStateChanged(evt);
            }
        });

        cmbRemark.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Remarks" }));
        cmbRemark.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbRemarkItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlFiltersLayout = new javax.swing.GroupLayout(pnlFilters);
        pnlFilters.setLayout(pnlFiltersLayout);
        pnlFiltersLayout.setHorizontalGroup(
            pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbParty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbLocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSupplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(cmbRemark, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlFiltersLayout.setVerticalGroup(
            pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbParty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRemark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No.", "Date", "Party", "Address", "Supplier", "Purchase", "Paid to DBC", "Sale", "Pay Received", "Remark"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(9).setResizable(false);
        }

        javax.swing.GroupLayout pnlDataLayout = new javax.swing.GroupLayout(pnlData);
        pnlData.setLayout(pnlDataLayout);
        pnlDataLayout.setHorizontalGroup(
            pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
        pnlDataLayout.setVerticalGroup(
            pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlSumLayout = new javax.swing.GroupLayout(pnlSum);
        pnlSum.setLayout(pnlSumLayout);
        pnlSumLayout.setHorizontalGroup(
            pnlSumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlSumLayout.setVerticalGroup(
            pnlSumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFilters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFilters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPartyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPartyItemStateChanged

        setTableData(data.get("SELECT * FROM Transactions WHERE "));
    }//GEN-LAST:event_cmbPartyItemStateChanged

    private void cmbLocationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbLocationItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLocationItemStateChanged

    private void cmbSupplierItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSupplierItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSupplierItemStateChanged

    private void cmbRemarkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbRemarkItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRemarkItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Summary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbLocation;
    private javax.swing.JComboBox<String> cmbParty;
    private javax.swing.JComboBox<String> cmbRemark;
    private javax.swing.JComboBox<String> cmbSupplier;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlData;
    private javax.swing.JPanel pnlFilters;
    private javax.swing.JPanel pnlSum;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    public void setFilteredTableData(){
        StringBuilder command = new StringBuilder("SELECT * FROM Transactions");
        if (cmbParty.getSelectedIndex()!=0){
            command.append("WHERE Party = '").append(cmbParty.getSelectedItem()).append("'");
        }
        if (cmbLocation.getSelectedIndex()!=0){
            if (command.toString().contains("WHERE"))command.append(" AND");
            else command.append(" WHERE");
            command.append(" Address = '").append(cmbLocation.getSelectedItem()).append("'");
        }
        if (cmbSupplier.getSelectedIndex()!=0){
            if (command.toString().contains("WHERE"))command.append(" AND");
            else command.append(" WHERE");
            command.append(" Supplier = '").append(cmbSupplier.getSelectedItem()).append("'");
        }
        if (cmbRemark.getSelectedIndex()!=0){
            if (command.toString().contains("WHERE"))command.append(" AND");
            else command.append(" WHERE");
            command.append(" Remark = '").append(cmbRemark.getSelectedItem()).append("'");
        }
    }
    public void setTableData(ResultSet set){
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        List<String> partyModel = new ArrayList<>();
        List<String> locModel = new ArrayList<>();
        List<String> supplierModel = new ArrayList<>();
        List<String> remarkModel = new ArrayList<>();
        String party,loc,supplier,remark;
        try {
            int i=1;
            while (set.next()){
                party = set.getString(2);
                loc = set.getString(3);
                supplier = set.getString(4);
                remark = set.getString(9);
                if (starting){
                    if (!partyModel.contains(party))partyModel.add(party);
                    if (!locModel.contains(loc))locModel.add(loc);
                    if (!supplierModel.contains(supplier))supplierModel.add(supplier);
                    if (!remarkModel.contains(remark))remarkModel.add(remark);
                }
                model.addRow(new Object[]{
                        i, set.getDate(1),party, loc, supplier,set.getFloat(5), set.getFloat(6),
                        set.getFloat(7), set.getFloat(8),remark
                });
                i++;
            }
            if (starting){
                ((DefaultComboBoxModel<String>)cmbParty.getModel()).addAll(partyModel);
                ((DefaultComboBoxModel<String>)cmbLocation.getModel()).addAll(locModel);
                ((DefaultComboBoxModel<String>)cmbSupplier.getModel()).addAll(supplierModel);
                ((DefaultComboBoxModel<String>)cmbRemark.getModel()).addAll(remarkModel);
            }
        }catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
