/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package me.rudraksha007.billgenerator.GUI;

import me.rudraksha007.billgenerator.AppFrame;
import me.rudraksha007.billgenerator.Main;
import me.rudraksha007.billgenerator.utilities.BillData;
import me.rudraksha007.billgenerator.utilities.DataManager;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.*;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.sql.Blob;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author rudra
 */
public class Summary extends javax.swing.JFrame {

    DataManager manager = new DataManager();
    boolean starting = true; //INFO: don't remove, adds all elements to CMBs
    AWTEventListener clickListener = new AWTEventListener() {
        @Override
        public void eventDispatched(AWTEvent event) {
            if (event.getID()!= MouseEvent.MOUSE_CLICKED)return;
            if (isTable((Component) event.getSource()))return;
            table.clearSelection();
            if (table.getCellEditor()!=null) table.getCellEditor().stopCellEditing();
        }
    };
    /** Creates new form Summary */
    public Summary() {
        initComponents();
        this.setLocationRelativeTo(null);
        manager.run("SELECT * FROM Transactions ORDER BY Date ASC");
        setTableData(manager.get("SELECT * FROM Transactions ORDER BY Date ASC"));
        dtFrom.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if (!evt.getPropertyName().equalsIgnoreCase("date"))return;
                dtTo.setMinSelectableDate(dtFrom.getDate());
                setFilteredTableData();
            }
        });
        dtTo.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if (!evt.getPropertyName().equalsIgnoreCase("date"))return;
                dtFrom.setMaxSelectableDate(dtTo.getDate());
                setFilteredTableData();
            }
        });
        starting = false;
        table.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting())return;
                btnEdit.setEnabled(table.getSelectedRow()>=0);
                btnDelete.setEnabled(table.getSelectedRow()>=0);
            }
        });
        Toolkit.getDefaultToolkit().addAWTEventListener(clickListener,AWTEvent.MOUSE_EVENT_MASK);
    }

    private boolean isTable(Component component){
        while (component!=null&&component!=table){
            if (component==btnEdit||component == btnDelete)return true;
            component = component.getParent();
        }
        return component==table;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        pnlFilters = new javax.swing.JPanel();
        cmbParty = new javax.swing.JComboBox<>();
        cmbSupplier = new javax.swing.JComboBox<>();
        cmbLocation = new javax.swing.JComboBox<>();
        cmbRemark = new javax.swing.JComboBox<>();
        dtFrom = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dtTo = new com.toedter.calendar.JDateChooser();
        cmbTransaction = new javax.swing.JComboBox<>();
        pnlData = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        pnlSum = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnAddTransaction = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        cmbParty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Party" }));
        cmbParty.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPartyItemStateChanged(evt);
            }
        });

        cmbSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supplier" }));
        cmbSupplier.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSupplierItemStateChanged(evt);
            }
        });

        cmbLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Location" }));
        cmbLocation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbLocationItemStateChanged(evt);
            }
        });

        cmbRemark.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Remarks" }));
        cmbRemark.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbRemarkItemStateChanged(evt);
            }
        });

        jLabel1.setText("From");

        jLabel2.setText("To");

        cmbTransaction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Transactions", "Purchased", "Paid_to_DBC", "Sale", "Received" }));
        cmbTransaction.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTransactionItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlFiltersLayout = new javax.swing.GroupLayout(pnlFilters);
        pnlFilters.setLayout(pnlFiltersLayout);
        pnlFiltersLayout.setHorizontalGroup(
            pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlFiltersLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(16, 16, 16)
                        .addComponent(dtFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cmbParty, 0, 306, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFiltersLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cmbLocation, 0, 306, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTransaction, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbSupplier, 0, 303, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addComponent(cmbRemark, 0, 303, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlFiltersLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        pnlFiltersLayout.setVerticalGroup(
            pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbParty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRemark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dtFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dtTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No.", "Invoice No.", "Date", "Party", "Address", "Supplier", "Purchased", "Paid_to_DBC", "Sale", "Received", "Remark"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(10).setResizable(false);
        }

        javax.swing.GroupLayout pnlDataLayout = new javax.swing.GroupLayout(pnlData);
        pnlData.setLayout(pnlDataLayout);
        pnlDataLayout.setHorizontalGroup(
            pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
        );
        pnlDataLayout.setVerticalGroup(
            pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );

        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);
        btnDelete.setFocusPainted(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.setEnabled(false);
        btnEdit.setFocusPainted(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAddTransaction.setText("Add");
        btnAddTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTransactionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSumLayout = new javax.swing.GroupLayout(pnlSum);
        pnlSum.setLayout(pnlSumLayout);
        pnlSumLayout.setHorizontalGroup(
            pnlSumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSumLayout.createSequentialGroup()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddTransaction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addContainerGap())
        );
        pnlSumLayout.setVerticalGroup(
            pnlSumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnBack)
                    .addComponent(btnEdit)
                    .addComponent(btnAddTransaction))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFilters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFilters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel3.setText("Summary");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPartyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPartyItemStateChanged
        if (evt.getStateChange()!= ItemEvent.SELECTED)return;
        setFilteredTableData();
    }//GEN-LAST:event_cmbPartyItemStateChanged

    private void cmbLocationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbLocationItemStateChanged
        cmbPartyItemStateChanged(evt);
    }//GEN-LAST:event_cmbLocationItemStateChanged

    private void cmbSupplierItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSupplierItemStateChanged
        cmbPartyItemStateChanged(evt);
    }//GEN-LAST:event_cmbSupplierItemStateChanged

    private void cmbRemarkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbRemarkItemStateChanged
        cmbPartyItemStateChanged(evt);
    }//GEN-LAST:event_cmbRemarkItemStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (evt!=null){
            Main.frames.get(AppFrame.home).setVisible(true);
        }
        Toolkit.getDefaultToolkit().removeAWTEventListener(clickListener);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        ResultSet set = manager.get("SELECT * FROM Bills WHERE InvoiceNo = '"+table.getValueAt(table.getSelectedRow(), 1)+"'");
        try {
            if (!set.next()){
                JOptionPane.showMessageDialog(this,"This bill doesn't exist, or was generated by other party"
                        , "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String serialized = set.getString(2);
            Bill b = new Bill();
            b.setVisible(true);
            b.setBill(new BillData(serialized));
            formWindowClosing(null);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        manager.run("DELETE FROM Transactions WHERE InvoiceNo = '"+table.getValueAt(table.getSelectedRow(),1)+"'AND Date = '"
                +Date.valueOf(String.valueOf(table.getValueAt(table.getSelectedRow(), 2)))+"' AND Purchased = "+
                Float.parseFloat(String.valueOf(table.getValueAt(table.getSelectedRow(), 6)))+" AND Paid_to_DBC = "+
                Float.parseFloat(String.valueOf(table.getValueAt(table.getSelectedRow(), 7)))+" AND Sale = "+
                Float.parseFloat(String.valueOf(table.getValueAt(table.getSelectedRow(), 8)))+" AND Received = "+
                Float.parseFloat(String.valueOf(table.getValueAt(table.getSelectedRow(), 9))));
        if (table.getValueAt(table.getSelectedRow(), 1)!=" "){
            manager.run("DELETE FROM Bills WHERE InvoiceNo = '"+table.getValueAt(table.getSelectedRow(), 1)+"'");
        }
        ((DefaultTableModel)table.getModel()).removeRow(table.getSelectedRow());

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Main.frames.get("home").setVisible(true);
        Toolkit.getDefaultToolkit().removeAWTEventListener(clickListener);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbTransactionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTransactionItemStateChanged
        if (evt.getStateChange()!=ItemEvent.SELECTED)return;
        setFilteredTableData();
    }//GEN-LAST:event_cmbTransactionItemStateChanged

    private void btnAddTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTransactionActionPerformed
        AddTransaction dialogue = new AddTransaction(this, true);
        dialogue.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {

            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                if (dialogue.party==null)return;
                String address,supplier;
                ResultSet set = manager.get("SELECT * FROM Parties WHERE Name = '"+dialogue.party+"'");
                try {
                    if (!set.next())return;
                    address = set.getString(2);
                    supplier = set.getString(4);
                } catch (SQLException ex) {
                    throw new RuntimeException(ex);
                }
                manager.addTransactionEntry(dialogue.date, dialogue.party,address,supplier,
                        DataManager.EntryType.valueOf(dialogue.transaction.toUpperCase()),dialogue.value,dialogue.remark,"-");
                setFilteredTableData();
            }

            @Override
            public void windowIconified(WindowEvent e) {

            }

            @Override
            public void windowDeiconified(WindowEvent e) {

            }

            @Override
            public void windowActivated(WindowEvent e) {

            }

            @Override
            public void windowDeactivated(WindowEvent e) {

            }
        });
        dialogue.setVisible(true);
    }//GEN-LAST:event_btnAddTransactionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Summary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTransaction;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<String> cmbLocation;
    private javax.swing.JComboBox<String> cmbParty;
    private javax.swing.JComboBox<String> cmbRemark;
    private javax.swing.JComboBox<String> cmbSupplier;
    private javax.swing.JComboBox<String> cmbTransaction;
    private com.toedter.calendar.JDateChooser dtFrom;
    private com.toedter.calendar.JDateChooser dtTo;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlData;
    private javax.swing.JPanel pnlFilters;
    private javax.swing.JPanel pnlSum;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    public void setFilteredTableData(){
        StringBuilder command = new StringBuilder("SELECT * FROM Transactions");
        if (cmbParty.getSelectedIndex()!=0){
            command.append(" WHERE Party = '").append(cmbParty.getSelectedItem()).append("'");
        }
        if (cmbLocation.getSelectedIndex()!=0){
            addConditionSeperator(command);
            command.append(" Address = '").append(cmbLocation.getSelectedItem()).append("'");
        }
        if (cmbSupplier.getSelectedIndex()!=0){
            addConditionSeperator(command);
            command.append(" Supplier = '").append(cmbSupplier.getSelectedItem()).append("'");
        }
        if (cmbRemark.getSelectedIndex()!=0){
            addConditionSeperator(command);
            command.append(" Remark = '").append(cmbRemark.getSelectedItem()).append("'");
        }
        if (dtFrom.getDate()!=null){
            addConditionSeperator(command);
            command.append(" Date > '").append(Date.valueOf(LocalDate.ofInstant(dtFrom.getDate().toInstant(), ZoneId.systemDefault())))
                    .append("'");
        }
        if (dtTo.getDate()!=null){
            addConditionSeperator(command);
            command.append(" Date < '").append(Date.valueOf(LocalDate.ofInstant(dtTo.getDate().toInstant(), ZoneId.systemDefault())))
                    .append("'");
        }
        if (cmbTransaction.getSelectedIndex()!=0){
            addConditionSeperator(command);
            command.append(" ").append(cmbTransaction.getSelectedItem()).append(" > 0");
        }
        command.append(" ORDER BY Date ASC");
        setTableData(manager.get(command.toString()));
    }
    public void setTableData(ResultSet set){
        if (set==null)return;
        ((DefaultTableModel)table.getModel()).setRowCount(0);
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        List<String> partyModel = new ArrayList<>();
        List<String> locModel = new ArrayList<>();
        List<String> supplierModel = new ArrayList<>();
        List<String> remarkModel = new ArrayList<>();
        String loc,supplier,remark;
        try {
            int i=1;
            while (set.next()){
                loc = set.getString(4);
                supplier = set.getString(5);
                remark = set.getString(10);
                if (starting){
                    if (!locModel.contains(loc))locModel.add(loc);
                    if (!supplierModel.contains(supplier))supplierModel.add(supplier);
                    if (!remarkModel.contains(remark))remarkModel.add(remark);
                }
                model.addRow(new Object[]{
                        i, set.getString(1),set.getDate(2),set.getString(3), loc, supplier,set.getFloat(6), set.getFloat(7),
                        set.getFloat(8), set.getFloat(9),remark
                });
                i++;
            }
            if (starting){
                set = manager.get("SELECT * FROM Parties");
                DefaultComboBoxModel<String> mod = (DefaultComboBoxModel<String>) cmbParty.getModel();
                while (set.next()){
                    mod.addElement(set.getString(1));
                }
                cmbParty.setModel(mod);
                set.getStatement().close();
                ((DefaultComboBoxModel<String>)cmbLocation.getModel()).addAll(locModel);
                ((DefaultComboBoxModel<String>)cmbSupplier.getModel()).addAll(supplierModel);
                ((DefaultComboBoxModel<String>)cmbRemark.getModel()).addAll(remarkModel);
            }
        }catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public StringBuilder addConditionSeperator(StringBuilder s){
        if (s.toString().contains("WHERE"))s.append(" AND");
        else s.append(" WHERE");
        return s;
    }
}
