/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package me.rudraksha007.billgenerator.GUI2;

/**
 *
 * @author rudra
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPane = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblBill = new javax.swing.JLabel();
        lblAddProduct = new javax.swing.JLabel();
        lblAddParty = new javax.swing.JLabel();
        lblEdit = new javax.swing.JLabel();
        lblSummary = new javax.swing.JLabel();
        ContentPane = new javax.swing.JLayeredPane();
        pnlBill = new javax.swing.JPanel();
        pnlInputs = new javax.swing.JPanel();
        InputLine1 = new javax.swing.JPanel();
        lblParty = new javax.swing.JLabel();
        cmbParty = new javax.swing.JComboBox<>();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        lblGst = new javax.swing.JLabel();
        txtGst = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSupplier = new javax.swing.JTextField();
        InputLine2 = new javax.swing.JPanel();
        lblInvoice = new javax.swing.JLabel();
        txtInvoice = new javax.swing.JTextField();
        lblInvoiceDate = new javax.swing.JLabel();
        dataChooser = new com.toedter.calendar.JDateChooser();
        lblVehicleNo = new javax.swing.JLabel();
        txtVehicle = new javax.swing.JTextField();
        lblRemarks = new javax.swing.JLabel();
        txtRemarks = new javax.swing.JTextField();
        BillData = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        pnlButtons = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblTax = new javax.swing.JLabel();
        txtTax = new javax.swing.JTextField();
        lblGTotal = new javax.swing.JLabel();
        txtGTotal = new javax.swing.JTextField();
        pnlAddProduct = new javax.swing.JPanel();
        pnlAddParty = new javax.swing.JPanel();
        pnlEdit = new javax.swing.JPanel();
        pnlSummary = new javax.swing.JPanel();
        pnlInfo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPane.setLayout(new java.awt.BorderLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/profile.png"))); // NOI18N
        jLabel5.setText("Portfolio");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlMenu.add(jLabel5);

        lblBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BillGen.png"))); // NOI18N
        lblBill.setText("New Bill");
        lblBill.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblBill.setMaximumSize(new java.awt.Dimension(80, 80));
        lblBill.setMinimumSize(new java.awt.Dimension(80, 80));
        lblBill.setPreferredSize(new java.awt.Dimension(80, 80));
        lblBill.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlMenu.add(lblBill);

        lblAddProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/AddProduct.png"))); // NOI18N
        lblAddProduct.setText("Add Product");
        lblAddProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAddProduct.setMaximumSize(new java.awt.Dimension(40, 40));
        lblAddProduct.setMinimumSize(new java.awt.Dimension(40, 40));
        lblAddProduct.setPreferredSize(new java.awt.Dimension(80, 80));
        lblAddProduct.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlMenu.add(lblAddProduct);

        lblAddParty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddParty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/AddParty.png"))); // NOI18N
        lblAddParty.setText("Add Party");
        lblAddParty.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAddParty.setMaximumSize(new java.awt.Dimension(40, 40));
        lblAddParty.setMinimumSize(new java.awt.Dimension(40, 40));
        lblAddParty.setPreferredSize(new java.awt.Dimension(80, 80));
        lblAddParty.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlMenu.add(lblAddParty);

        lblEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Edit.png"))); // NOI18N
        lblEdit.setText("Edit Your Data");
        lblEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEdit.setMaximumSize(new java.awt.Dimension(40, 40));
        lblEdit.setMinimumSize(new java.awt.Dimension(40, 40));
        lblEdit.setPreferredSize(new java.awt.Dimension(80, 80));
        lblEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlMenu.add(lblEdit);

        lblSummary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSummary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/summary.png"))); // NOI18N
        lblSummary.setText("Summary");
        lblSummary.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSummary.setMaximumSize(new java.awt.Dimension(40, 40));
        lblSummary.setMinimumSize(new java.awt.Dimension(40, 40));
        lblSummary.setPreferredSize(new java.awt.Dimension(80, 80));
        lblSummary.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlMenu.add(lblSummary);

        MainPane.add(pnlMenu, java.awt.BorderLayout.PAGE_START);

        ContentPane.setLayout(new javax.swing.OverlayLayout(ContentPane));

        pnlBill.setLayout(new java.awt.BorderLayout());

        pnlInputs.setLayout(new java.awt.BorderLayout());

        lblParty.setText("Party");
        InputLine1.add(lblParty);

        cmbParty.setPreferredSize(new java.awt.Dimension(200, 22));
        InputLine1.add(cmbParty);

        lblAddress.setText("Address");
        InputLine1.add(lblAddress);

        txtAddress.setEditable(false);
        txtAddress.setPreferredSize(new java.awt.Dimension(200, 22));
        InputLine1.add(txtAddress);

        lblState.setText("State");
        InputLine1.add(lblState);

        txtState.setEditable(false);
        txtState.setPreferredSize(new java.awt.Dimension(200, 22));
        InputLine1.add(txtState);

        lblGst.setText("GSTIN");
        InputLine1.add(lblGst);

        txtGst.setEditable(false);
        txtGst.setPreferredSize(new java.awt.Dimension(200, 22));
        InputLine1.add(txtGst);

        jLabel6.setText("Supplier");
        jLabel6.setPreferredSize(new java.awt.Dimension(50, 16));
        InputLine1.add(jLabel6);

        txtSupplier.setPreferredSize(new java.awt.Dimension(200, 22));
        InputLine1.add(txtSupplier);

        pnlInputs.add(InputLine1, java.awt.BorderLayout.PAGE_START);

        lblInvoice.setText("Invoice No.");
        InputLine2.add(lblInvoice);

        txtInvoice.setPreferredSize(new java.awt.Dimension(200, 22));
        InputLine2.add(txtInvoice);

        lblInvoiceDate.setText("Invoice Date");
        lblInvoiceDate.setPreferredSize(new java.awt.Dimension(70, 16));
        InputLine2.add(lblInvoiceDate);

        dataChooser.setPreferredSize(new java.awt.Dimension(200, 22));
        InputLine2.add(dataChooser);

        lblVehicleNo.setText("Vehicle No.");
        InputLine2.add(lblVehicleNo);

        txtVehicle.setPreferredSize(new java.awt.Dimension(200, 22));
        InputLine2.add(txtVehicle);

        lblRemarks.setText("Remarks");
        InputLine2.add(lblRemarks);

        txtRemarks.setPreferredSize(new java.awt.Dimension(200, 22));
        InputLine2.add(txtRemarks);

        pnlInputs.add(InputLine2, java.awt.BorderLayout.CENTER);

        pnlBill.add(pnlInputs, java.awt.BorderLayout.PAGE_START);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No.", "Product Description", "HSN Code", "Quantity", "Rate", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(63);
            table.getColumnModel().getColumn(0).setPreferredWidth(63);
            table.getColumnModel().getColumn(0).setMaxWidth(63);
            table.getColumnModel().getColumn(2).setMinWidth(150);
            table.getColumnModel().getColumn(2).setPreferredWidth(150);
            table.getColumnModel().getColumn(2).setMaxWidth(150);
            table.getColumnModel().getColumn(3).setMinWidth(80);
            table.getColumnModel().getColumn(3).setPreferredWidth(80);
            table.getColumnModel().getColumn(3).setMaxWidth(80);
            table.getColumnModel().getColumn(4).setMinWidth(126);
            table.getColumnModel().getColumn(4).setPreferredWidth(126);
            table.getColumnModel().getColumn(4).setMaxWidth(126);
            table.getColumnModel().getColumn(5).setMinWidth(150);
            table.getColumnModel().getColumn(5).setPreferredWidth(150);
            table.getColumnModel().getColumn(5).setMaxWidth(150);
        }

        javax.swing.GroupLayout BillDataLayout = new javax.swing.GroupLayout(BillData);
        BillData.setLayout(BillDataLayout);
        BillDataLayout.setHorizontalGroup(
            BillDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BillDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1264, Short.MAX_VALUE)
                .addContainerGap())
        );
        BillDataLayout.setVerticalGroup(
            BillDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );

        pnlBill.add(BillData, java.awt.BorderLayout.CENTER);

        pnlButtons.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/AddItem.png"))); // NOI18N
        jLabel1.setText("Add Item");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/RemoveItem.png"))); // NOI18N
        jLabel2.setText("Remove Item");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel2);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cancel.png"))); // NOI18N
        jLabel3.setText("Cancel");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel3);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Save.png"))); // NOI18N
        jLabel4.setText("Save");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel4);

        pnlButtons.add(jPanel1, java.awt.BorderLayout.CENTER);

        lblTotal.setText("Total: ");
        lblTotal.setPreferredSize(new java.awt.Dimension(32, 22));
        jPanel2.add(lblTotal);

        txtTotal.setEditable(false);
        txtTotal.setText("0.0");
        txtTotal.setPreferredSize(new java.awt.Dimension(200, 22));
        jPanel2.add(txtTotal);

        lblTax.setText("Tax:");
        jPanel2.add(lblTax);

        txtTax.setEditable(false);
        txtTax.setText("0.0");
        txtTax.setPreferredSize(new java.awt.Dimension(200, 22));
        jPanel2.add(txtTax);

        lblGTotal.setText("Total + Tax: ");
        jPanel2.add(lblGTotal);

        txtGTotal.setEditable(false);
        txtGTotal.setText("0.0");
        txtGTotal.setPreferredSize(new java.awt.Dimension(200, 22));
        jPanel2.add(txtGTotal);

        pnlButtons.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pnlBill.add(pnlButtons, java.awt.BorderLayout.PAGE_END);

        ContentPane.add(pnlBill);

        javax.swing.GroupLayout pnlAddProductLayout = new javax.swing.GroupLayout(pnlAddProduct);
        pnlAddProduct.setLayout(pnlAddProductLayout);
        pnlAddProductLayout.setHorizontalGroup(
            pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1276, Short.MAX_VALUE)
        );
        pnlAddProductLayout.setVerticalGroup(
            pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );

        ContentPane.add(pnlAddProduct);

        javax.swing.GroupLayout pnlAddPartyLayout = new javax.swing.GroupLayout(pnlAddParty);
        pnlAddParty.setLayout(pnlAddPartyLayout);
        pnlAddPartyLayout.setHorizontalGroup(
            pnlAddPartyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1276, Short.MAX_VALUE)
        );
        pnlAddPartyLayout.setVerticalGroup(
            pnlAddPartyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );

        ContentPane.add(pnlAddParty);

        javax.swing.GroupLayout pnlEditLayout = new javax.swing.GroupLayout(pnlEdit);
        pnlEdit.setLayout(pnlEditLayout);
        pnlEditLayout.setHorizontalGroup(
            pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1276, Short.MAX_VALUE)
        );
        pnlEditLayout.setVerticalGroup(
            pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );

        ContentPane.add(pnlEdit);

        javax.swing.GroupLayout pnlSummaryLayout = new javax.swing.GroupLayout(pnlSummary);
        pnlSummary.setLayout(pnlSummaryLayout);
        pnlSummaryLayout.setHorizontalGroup(
            pnlSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1276, Short.MAX_VALUE)
        );
        pnlSummaryLayout.setVerticalGroup(
            pnlSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );

        ContentPane.add(pnlSummary);

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1276, Short.MAX_VALUE)
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );

        ContentPane.add(pnlInfo);

        MainPane.add(ContentPane, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BillData;
    private javax.swing.JLayeredPane ContentPane;
    private javax.swing.JPanel InputLine1;
    private javax.swing.JPanel InputLine2;
    private javax.swing.JPanel MainPane;
    private javax.swing.JComboBox<String> cmbParty;
    private com.toedter.calendar.JDateChooser dataChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddParty;
    private javax.swing.JLabel lblAddProduct;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBill;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JLabel lblGTotal;
    private javax.swing.JLabel lblGst;
    private javax.swing.JLabel lblInvoice;
    private javax.swing.JLabel lblInvoiceDate;
    private javax.swing.JLabel lblParty;
    private javax.swing.JLabel lblRemarks;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblSummary;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVehicleNo;
    private javax.swing.JPanel pnlAddParty;
    private javax.swing.JPanel pnlAddProduct;
    private javax.swing.JPanel pnlBill;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlEdit;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlInputs;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlSummary;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtGTotal;
    private javax.swing.JTextField txtGst;
    private javax.swing.JTextField txtInvoice;
    private javax.swing.JTextField txtRemarks;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtSupplier;
    private javax.swing.JTextField txtTax;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtVehicle;
    // End of variables declaration//GEN-END:variables
}
