/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package me.rudraksha007.billgenui.GUI;

import me.rudraksha007.billgenui.*;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
import java.util.*;
import java.util.Timer;

/**
 *
 * @author rudra
 */
public class AddProduct extends javax.swing.JFrame {

    /**
     * Creates new form AddProduct
     */
    public AddProduct() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnCancel.setFocusPainted(false);
        btnClear.setFocusPainted(false);
        btnSave.setFocusPainted(false);
        btnAdd.setFocusPainted(false);
        btnDelete.setFocusPainted(false);
        tblSizes.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                btnDelete.setEnabled(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbBrands = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cmbProduct = new javax.swing.JComboBox<>();
        sprCost = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSizes = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Add Product");
        setMinimumSize(new java.awt.Dimension(450, 470));
        setPreferredSize(new java.awt.Dimension(450, 470));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Brand Name");

        cmbBrands.setEditable(true);
        cmbBrands.setAutoscrolls(true);
        cmbBrands.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBrandsItemStateChanged(evt);
            }
        });

        jLabel2.setText("Product Name");

        jLabel3.setText("Size and Cost");

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(2);
        jTextArea1.setText("Enter the size value and press enter to add\nEnter new Brand (in the box) to add");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea1);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Size");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Clear ");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        cmbProduct.setEditable(true);
        cmbProduct.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbProductItemStateChanged(evt);
            }
        });

        tblSizes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Size", "Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSizes.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblSizes);
        if (tblSizes.getColumnModel().getColumnCount() > 0) {
            tblSizes.getColumnModel().getColumn(0).setResizable(false);
            tblSizes.getColumnModel().getColumn(1).setResizable(false);
        }

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSave))
                        .addComponent(jScrollPane2)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(8, 8, 8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbProduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbBrands, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sprCost, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnAdd))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnDelete)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBrands, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sprCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdd)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnDelete))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String Brand = ((JTextField) cmbBrands.getEditor().getEditorComponent()).getText().trim();
        if (Brand.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter Brand Name First!"
            , "Enter Brand", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String Name = ((JTextField) cmbProduct.getEditor().getEditorComponent()).getText().trim();
        Map<String, Integer>sizes = new HashMap<>();
        if (this.tblSizes.getModel().getRowCount()<1){
            JOptionPane.showMessageDialog(this, "Please Add at least 1 size"
                    , "Add Size", JOptionPane.ERROR_MESSAGE);

            return;
        }
        for (int i = 0; i < this.tblSizes.getModel().getRowCount(); i++) {
            sizes.put(String.valueOf(this.tblSizes.getModel().getValueAt(i,0)),
                    Integer.parseInt(String.valueOf(this.tblSizes.getModel().getValueAt(i,1))));
        }
        Item item = new Item(Name,Brand,sizes);
        if (Main.items.containsKey(Brand)){
            for (Item i: Main.items.get(Brand)){
                if (!i.getName().equals(Name))continue;
                i.setSizes(sizes);
            }
            for (Item i: Main.allItems){
                if (!i.getName().equals(Name))continue;
                i.setSizes(sizes);
            }
        }else {
            Main.items.put(Brand, Collections.singletonList(item));
            Main.allItems.add(item);
        }
        new DataManager().saveData();
        Main.frames.get(AppFrame.HOME.toString()).setVisible(true);
        this.setVisible(false);
        clearForm();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setVisible(false);
        Main.frames.get("home").setVisible(true);
        clearForm();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        btnCancelActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing

    private void cmbBrandsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBrandsItemStateChanged
        if (evt.getStateChange()== ItemEvent.SELECTED){
            DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) cmbProduct.getModel();
            model.removeAllElements();
            model.addElement("");
            if (!(cmbBrands.getSelectedIndex() >0)){
                return;
            }
            if (Main.items.containsKey(String.valueOf(cmbBrands.getSelectedItem()))){
                int i =1;
                for (Item item: Main.items.get(String.valueOf(evt.getItem()))){
                    if (model.getElementAt(i)!=null)if (model.getElementAt(i).equals(item.getName()))continue;
                    model.addElement(item.getName());
                }
                cmbProduct.setModel(model);
            }
        }
    }//GEN-LAST:event_cmbBrandsItemStateChanged

    private void cmbProductItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbProductItemStateChanged
        if (evt.getStateChange()==ItemEvent.SELECTED){
            if (!(cmbProduct.getSelectedIndex()>0))return;
            String brand = String.valueOf(cmbBrands.getSelectedItem());
            List<Item>itemList = Main.items.get(brand);
            for (Item i: itemList){
                if (!i.getName().equals(String.valueOf(cmbProduct.getSelectedItem())))continue;
                DefaultTableModel mod = (DefaultTableModel) tblSizes.getModel();
                mod.setRowCount(i.getSizes().size());
                Object[][] data = new Object[i.getSizes().size()][i.getSizes().size()];
                int j = 0;
                for (Map.Entry<String,Integer> entry: i.getSizes().entrySet()){
                    data[j]=new Object[]{entry.getKey(), entry.getValue()};
                    j++;
                }
                mod.setDataVector(data, new String[]{"Size", "Cost"});
                tblSizes.setModel(mod);
            }

        }
    }//GEN-LAST:event_cmbProductItemStateChanged

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String size = txtSize.getText().trim();
        if (size.isEmpty())return;
        float cost = Float.parseFloat(String.valueOf(sprCost.getModel().getValue()));
        if (cost<=0)return;
        DefaultTableModel model = (DefaultTableModel) tblSizes.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i,0).equals(size)){
                txtSize.setText(null);
                sprCost.setValue(0);
                return;
            }
        }
        model.insertRow(model.getRowCount(), new Object[]{txtSize.getText().trim(),
                Integer.parseInt(String.valueOf(sprCost.getValue()))});
        txtSize.setText(null);
        sprCost.setValue(0);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (!(tblSizes.getSelectedRow() >=0))return;
        DefaultTableModel model = (DefaultTableModel) tblSizes.getModel();
        model.removeRow(tblSizes.getSelectedRow());
        tblSizes.setModel(model);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        tblSizes.clearSelection();
        btnDelete.setEnabled(false);
    }//GEN-LAST:event_formMouseClicked

    public void clearForm(){
        cmbBrands.setSelectedIndex(0);
        cmbProduct.setModel(new DefaultComboBoxModel<>(new String[]{""}));
        cmbProduct.setSelectedIndex(0);

        txtSize.setText("");
        for (int i = 0; i < 2; i++) {
            for (int j = 0; j < tblSizes.getModel().getRowCount(); j++) {
                tblSizes.getModel().setValueAt(null, j, i);
            }
        }
        DefaultTableModel model = (DefaultTableModel) tblSizes.getModel();
        model.setRowCount(0);
        tblSizes.setModel(model);
    }

    public void updateBrands(){
        if (Main.items !=null && Main.items.keySet().size()!=0){
            String[] modelData = new String[Main.items.keySet().size()+1];
            modelData[0] = "";
            int i=1;
            for(String key: Main.items.keySet()){
                modelData[i] = key;
                i++;
            }
            cmbBrands.setModel(new javax.swing.DefaultComboBoxModel<>(modelData));
        } else cmbBrands.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{""}));
    }

    @Override
    public void setVisible(boolean visible){
        super.setVisible(visible);
        if (visible)updateBrands();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddProduct().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbBrands;
    private javax.swing.JComboBox<String> cmbProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JSpinner sprCost;
    private javax.swing.JTable tblSizes;
    private javax.swing.JTextField txtSize;
    // End of variables declaration//GEN-END:variables
}
